### ISSUE TITLE
Putting a label to the side of Auto-Complete box

### ISSUE THREAD

**Issue by rmwilliamsuk** [pawelczak/EasyAutocomplete#292]
I am trying to put a label to the left of the easy-autocomplete field.

My HTML is fairly simple:

<div class='formfield'>
<label class='field' name='lbl_location_id' id='lbl_location_id'>Location</label>
<input id='location_id' name='location_id' style='text-transform: uppercase' maxlength=20 />
</div>

Location_id is the name of my easy-autocomplete field.

The label always appears above the easy-autocomplete field. Is there something that forces this?

**Comment by hosein2398** [comment]
@rmwilliamsuk 
Change class of `.easy-autocomplete` in plugin's `easy-autocomplete.css` file like this:
```css
.easy-autocomplete {
  position: relative;
  display : inline !important;
}
```
